name: insta
description: Instagram UI clone using flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.1
  provider: ^5.0.0
  fluttertoast: ^8.0.3
  pin_code_fields: ^6.0.0
  pinch_zoom: ^0.1.0 
  scrolling_page_indicator: ^0.1.3
  flutter_staggered_grid_view: ^0.3.4
  day_night_switcher: ^0.2.0+1
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  flutter_colorpicker: ^0.4.0
  before_after: ^2.1.0 
  path_provider: ^2.0.1 
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - resources/
  fonts:
    - family: Gilroy
      fonts:
        - asset: resources/fonts/Gilroy-Medium.ttf
        - asset: resources/fonts/Gilroy-Bold.ttf
          weight: 700